### ISSUE TITLE
Spring Boot

### ISSUE THREAD

**Issue by shuklaalok7** [axd164330/Library#2]
Another suggestion.

We can upgrade `Services` to Spring Boot, that can use embedded Tomcat thus changing packaging from `war` to `jar` and making it easier to deploy.

**Comment by shuklaalok7** [comment]
I may send a PR for this.

**Comment by asdhammu** [comment]
We can do that. This was just a pet project. We can get rid of database layer and use the spring data as that is more efficient as it uses hikari pool internally. This would also help to get rid of the database scripts, as the spring data would create the tables once the applications starts.

**Comment by asdhammu** [comment]
This has been implemented
